# Generated by Django 3.2.21 on 2024-02-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('tall', 'Tall')], max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
