# Generated by Django 3.2.21 on 2024-02-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20240229_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('small', 'Small'), ('smaller', 'Smaller'), ('medium', 'Medium'), ('tall', 'Tall')], max_length=10),
        ),
    ]
