# Generated by Django 5.0.2 on 2024-03-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_image_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("wedding_venue", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("time_sent", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
