# Generated by Django 3.2.21 on 2024-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('long', 'Long'), ('medium', 'Medium'), ('tall', 'Tall')], max_length=10),
        ),
    ]
