# Generated by Django 3.2.21 on 2024-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='gif_image',
            field=models.ImageField(blank=True, null=True, upload_to='discount_gifs/'),
        ),
    ]
