# Generated by Django 3.2.21 on 2024-03-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_discount_gif_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
