# Generated by Django 3.2.21 on 2024-03-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_image_larger_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='larger_image',
            field=models.ImageField(blank=True, null=True, upload_to='larger-images/'),
        ),
    ]
